[project]
name = "psup-validator"
version = "0.1.0"
description = "Validates the PSUP STAC Catalog"
readme = "README.md"
authors = [{ name = "Shadi Boomi", email = "shadi.boomi@universite-paris-saclay.fr" }]
requires-python = ">=3.13"
license = { file = "LICENSE" }
keywords = ["gis", "planetary science", "pydantic", "pystac", "stac"]
dependencies = [
  "jsonschema>=4.26.0",
  "pystac>=1.15.2",
  "stac-pydantic-extensions>=0.1.0",
  "typer>=0.27.2",
]
classifiers = ["Development Status :: 3 - Alpha", "Framework :: Pydantic", "Intended Audience :: Developers", "Intended Audience :: Science/Research", "License :: OSI Approved :: Common Development and Distribution License 1.0 (CDDL-1.0)", "Private :: Do Not Upload", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14", "Topic :: Scientific/Engineering :: GIS", "Topic :: Utilities", "Typing :: Typed"]

[project.urls]
Homepage = "https://github.com/pdssp/psup-scraper"
Issues = "https://github.com/pdssp/psup-scraper/issues"
Repository = "https://github.com/pdssp/psup-scraper"

[project.scripts]
psup-validator = "psup_validator.cli:app"

[dependency-groups]
dev = [
  "prek>=0.5.1",
  "ruff>=0.16.5",
  "tombi>=1.5.0",
  "ty>=0.0.77",
]
test = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-xdist>=3.8.0",
]

[build-system]
requires = ["uv_build>=0.11.9,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
filterwarnings = ["error"]
testpaths = ["tests"]

[tool.ty.src]
include = ["src"]
exclude = [".venv", "tests"]

[tool.ty.environment]
python = ".venv"
